### ISSUE TITLE
How to collect the cropped NYUD?

### ISSUE THREAD

**Issue by AkiyamaZw** [ricvolpi/adversarial_feature_augmentation#10]
It's a nice work of DIFA. 
Recently, I need to evaluate my own DA model on NYUD cropped datasets. And I follow the description of Tzeng[1] and tried to crop object in RGB and HHA images. However, the number of images in each category is not match to the discription of NYUD in [1] and experiments part of DIFA. Could you give me some suggests about the NYUD?

Many thanks.
[1]Tzeng, Eric, Judy Hoffman, Kate Saenko and Trevor Darrell. “Adversarial Discriminative Domain Adaptation.” 2017 IEEE Conference on Computer Vision and Pattern Recognition (CVPR) (2017): 2962-2971.

**Comment by pmorerio** [comment]
Hi, I think I have a matlab script doing the job somewhere, but I cannot find it.

I have used the same dataset in this multimodal learning project https://github.com/pmorerio/admd. Pleae feel free to download it (download link is in the README in the NYUD folder).

In the UDA setting, source is train/images, while target is test/depth. This is done in order to avoid having both depth and RGB for the same instance of an object.
Please note that the rest of the dataset was NOT used at all for our DIFA paper.

Best luck with your work,

P.

**Comment by pmorerio** [comment]
Just a quick note: the baseline accuracies for DIFA were obtained with a VGG, in order to be comparable with ADDA, which originally proposed this cross-modal adaptation task.
The code from the github page I linked you employs instead a Resnet50 and provides a higher baseline accuracy (at least for the train-on-target).
