### ISSUE TITLE
train_feature_extractor

### ISSUE THREAD

**Issue by omg777** [ricvolpi/adversarial_feature_augmentation#7]
Thanks for your nice paper and works.
I have some questions about contents of paper and implementation.

1) I don`t understand that why to use **Feature generator** that generates features that are similar to original source features **instead of source features**.

2) How can I draw t-SNE plots after make features using your code(with train_feature_extractor function)
    Can you tell me where`s the reference codes or yours?

thanks!

**Comment by ricvolpi** [comment]
Hi, 

1. We empirically observed that features generated through S (feature_generator in our code) show a broader variability, and playing the minimax game against these features instead of the original ones leads to better results. 

2. I applied the TSNE function from sklearn.metrics to the features extracted through feature_extractor, and plotted the first two components of the tsne representation with plt.scatter.
